# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Docli < Formula
  desc "DragonOps CLI to deploy and manage cloud infrastructure"
  homepage "https://github.com/DragonOps-io/homebrew-tap"
  version "0.0.23"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DragonOps-io/docli/releases/download/v0.0.23/docli_Darwin_x86_64.tar.gz"
      sha256 "66e8281810663192aa286a0a32ba70fba6beb71209bbd0349aee0c9c2b096dbc"

      def install
        bin.install "docli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DragonOps-io/docli/releases/download/v0.0.23/docli_Darwin_arm64.tar.gz"
      sha256 "dfc4f3c4b5767a8b80819923217a5a4abbc2efbcbfc386000e70eb45c27810f6"

      def install
        bin.install "docli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/DragonOps-io/docli/releases/download/v0.0.23/docli_Linux_armv6.tar.gz"
      sha256 "21fcf97198d5746668f0e5147a98461368decaf3953ce8d0ccffc432d45bea2b"

      def install
        bin.install "docli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DragonOps-io/docli/releases/download/v0.0.23/docli_Linux_x86_64.tar.gz"
      sha256 "50c122d53775d00ec2ea4c77907ca27731cd21b9c7284aa64fb8a49b018d60c4"

      def install
        bin.install "docli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DragonOps-io/docli/releases/download/v0.0.23/docli_Linux_arm64.tar.gz"
      sha256 "9f8c0adf51acc0e76329fd37b3181c20441c4ed6c85126308f9e1c0293e5dcad"

      def install
        bin.install "docli"
      end
    end
  end
end
