# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dragonops < Formula
  desc "DragonOps CLI to deploy and manage cloud infrastructure"
  homepage "https://github.com/DragonOps-io/homebrew-tap"
  version "0.0.130"

  on_macos do
    on_intel do
      url "https://dragonops-cli-releases.s3.amazonaws.com/dragonops-cli/0.0.130/docli_Darwin_x86_64.tar.gz"
      sha256 "4b63abea525a2213781bd6390cb008400c5cd451e12fecb263bbe26420923257"

      def install
        bin.install "dragonops"
      end
    end
    on_arm do
      url "https://dragonops-cli-releases.s3.amazonaws.com/dragonops-cli/0.0.130/docli_Darwin_arm64.tar.gz"
      sha256 "aaa533bdd7f78c62ac7178bba5fdee8313af1df4692eb8104d5b24972bbd19f1"

      def install
        bin.install "dragonops"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://dragonops-cli-releases.s3.amazonaws.com/dragonops-cli/0.0.130/docli_Linux_x86_64.tar.gz"
        sha256 "6b63be3c903f1de7b06a8a1c912ab6d1598d0179fac9d887e0ff8f081887ea25"

        def install
          bin.install "dragonops"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://dragonops-cli-releases.s3.amazonaws.com/dragonops-cli/0.0.130/docli_Linux_armv6.tar.gz"
        sha256 "4bbba6b261f3bc0a52ff7e07f0dd237f8301ef5104f0c35f14e36f44428388cc"

        def install
          bin.install "dragonops"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://dragonops-cli-releases.s3.amazonaws.com/dragonops-cli/0.0.130/docli_Linux_arm64.tar.gz"
        sha256 "f2c5b51a5607080f73ba6eeedd683359af0f769b91924922997fb1dab5f62264"

        def install
          bin.install "dragonops"
        end
      end
    end
  end
end
