# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dragonops < Formula
  desc "DragonOps CLI to deploy and manage cloud infrastructure"
  homepage "https://github.com/DragonOps-io/homebrew-tap"
  version "0.0.79"

  on_macos do
    if Hardware::CPU.intel?
      url "https://dragonops-cli-releases.s3.amazonaws.com/dragonops-cli/0.0.79/docli_Darwin_x86_64.tar.gz"
      sha256 "998ea8813ba381af2879c4a1af723ced5096086d5ed0b6d61e60356e6bbbb57d"

      def install
        bin.install "dragonops"
      end
    end
    if Hardware::CPU.arm?
      url "https://dragonops-cli-releases.s3.amazonaws.com/dragonops-cli/0.0.79/docli_Darwin_arm64.tar.gz"
      sha256 "9850bbbf3b9601ea3c4cc55df181741dd39ca7457cd0f5e9da3fdf65a1a3080e"

      def install
        bin.install "dragonops"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://dragonops-cli-releases.s3.amazonaws.com/dragonops-cli/0.0.79/docli_Linux_x86_64.tar.gz"
      sha256 "514e8a077e61a47b61f118b8f18f9129a6674d179e338a9083584a13ad1d86eb"

      def install
        bin.install "dragonops"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://dragonops-cli-releases.s3.amazonaws.com/dragonops-cli/0.0.79/docli_Linux_armv6.tar.gz"
      sha256 "a23f5c242e962f0faafe8f10ff3731c33766ae59ccb54611e996b4e71be34030"

      def install
        bin.install "dragonops"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://dragonops-cli-releases.s3.amazonaws.com/dragonops-cli/0.0.79/docli_Linux_arm64.tar.gz"
      sha256 "cb0c81dd50010672367920036f679848247228ab0aa74d38756cf77a04094d82"

      def install
        bin.install "dragonops"
      end
    end
  end
end
