# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Name < Formula
  desc "DragonOps CLI to deploy and manage cloud infrastructure"
  homepage "https://github.com/DragonOps-io/homebrew-tap"
  version "0.0.22"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DragonOps-io/docli/releases/download/v0.0.22/docli_Darwin_arm64.tar.gz"
      sha256 "02b4ab2c1195854cddf9aef5d7863befde20acfeadab71b0254da26bcc18502c"

      def install
        bin.install "docli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DragonOps-io/docli/releases/download/v0.0.22/docli_Darwin_x86_64.tar.gz"
      sha256 "b9fcf5d42aeb6db83ff3d81b43c7303a1df691ec697b0c656f6743312a3c7b91"

      def install
        bin.install "docli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/DragonOps-io/docli/releases/download/v0.0.22/docli_Linux_armv6.tar.gz"
      sha256 "389ab979bfc0fbaa961a08acb0c88f6953fd47d70e9019b4173c233aba7d763c"

      def install
        bin.install "docli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DragonOps-io/docli/releases/download/v0.0.22/docli_Linux_x86_64.tar.gz"
      sha256 "cca058d00dd9257b2b26e5f54573f6af776abacaaab6f5e2973c034a1ff0bea9"

      def install
        bin.install "docli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DragonOps-io/docli/releases/download/v0.0.22/docli_Linux_arm64.tar.gz"
      sha256 "77cd724fce06f27227a532607d26f26ab285fb7ef9b021d2a1526f20ba620e04"

      def install
        bin.install "docli"
      end
    end
  end
end
